brennanb_stats.o: brennanb_stats.cpp brennanb_stats.hpp
	$(CC) -c $^
.o: .cpp .hpp
	$(CC) -c $^
.o: .cpp .hpp
	$(CC) -c $^
brennanb_corr.o: brennanb_stats.o .o .o
	$(CC) -c /lab/bien4290/midterm2022/Simple $^
clean:
	rm -f *.o
all: brennanb_corr.o brennanb_stats.o .o .o
brennanb_stats.o: brennanb_stats.cpp brennanb_stats.hpp
	$(CC) -c $^
.o: .cpp .hpp
	$(CC) -c $^
.o: .cpp .hpp
	$(CC) -c $^
brennanb_corr.o: brennanb_stats.o .o .o
	$(CC) -c /lab/bien4290/midterm2022/Simple $^
clean:
	rm -f *.o
all: brennanb_corr.o brennanb_stats.o .o .o
